max_lines: 5
readme_path: 'README.md'
commit_message: '⚡ Update recent activity'
template: |
  | 🚀 Repository | 🛠️ Activity | 📅 Date |
  | :--- | :--- | :--- |
  | **[{repo}](https://github.com/m-farhan-hamim/{repo})** | {activity} | {date} |
